lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
<<<<<<< HEAD

=======
    token_ttl: '%env(int:ACCESS_TOKEN_TTL)%'
>>>>>>> link-admin
    token_extractors: 
        cookie: 
            enabled: true
            name: access_token

<<<<<<< HEAD
    set_cookies:
        access_token:
            lifetime: 3600
            samesite: 'none'
            path: /
            domain: null 
            secure: true
            httpOnly: true
=======
    # set_cookies:
    #     access_token:
    #         lifetime: 3600
    #         samesite: 'none'
    #         path: /
    #         domain: null 
    #         secure: true
    #         httpOnly: true
>>>>>>> link-admin
